// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAC6ziH8LeZeoMyz4bsNjp4A78V1D7oorQ',
    appId: '1:320374883326:web:ecb902c4ff3d8750b6b6af',
    messagingSenderId: '320374883326',
    projectId: 'charityappfyp',
    authDomain: 'charityappfyp.firebaseapp.com',
    storageBucket: 'charityappfyp.appspot.com',
    measurementId: 'G-T49KMWDY2J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDU8ntLRiDRdo_LM42vsVAd0mTvgALCZmY',
    appId: '1:320374883326:android:da8187bf872a60dab6b6af',
    messagingSenderId: '320374883326',
    projectId: 'charityappfyp',
    storageBucket: 'charityappfyp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRz_pKyR7OLAE7CyIDmHF3KfoNvltU_-M',
    appId: '1:320374883326:ios:bcb105d642d892f8b6b6af',
    messagingSenderId: '320374883326',
    projectId: 'charityappfyp',
    storageBucket: 'charityappfyp.appspot.com',
    iosBundleId: 'com.example.charityApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRz_pKyR7OLAE7CyIDmHF3KfoNvltU_-M',
    appId: '1:320374883326:ios:26927dff99493b9bb6b6af',
    messagingSenderId: '320374883326',
    projectId: 'charityappfyp',
    storageBucket: 'charityappfyp.appspot.com',
    iosBundleId: 'com.example.charityApp.RunnerTests',
  );
}
